# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa9e0dc3e374dc11807f5a09841dc35df3ad47029d9a5a06aec80992b1295f0a8d233d02d7be0d17a23b1e3910ef7ec3bbecc8ed3b781aac8504439ef5cb90e0

test:
  secret_key_base: 806cd6ea9c208a507b3dc856bfcb519adc7ea0dad7ce1ec7fcaba7122a34edada2d363910da2e463a93e4b7d8dbfbfc1f38f8fbc9986eace39ece08470a6a00b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 806cd6ea9c208a507b3dc856bfcb519adc7ea0dad7ce1ec7fcaba7122a34edada2d363910da2e463a93e4b7d8dbfbfc1f38f8fbc9986eace39ece08470a6a00b

  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
